/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package photomator;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class automator_window extends javax.swing.JDialog {

    /**
     * Creates new form automator_window
     */
    
    String log;
    
    Configuration actual_c;
    
    String wersja = "v1.0beta2";
    
    String path;
    
    ArrayList<Photo> file_list;
    
    public automator_window(java.awt.Frame parent, boolean modal,ArrayList<Photo> to_copy,String path,Configuration to_pass) {
        super(parent, modal);
        this.path = path;
        file_list = to_copy;
        actual_c = to_pass;
        
        initComponents();
        log = "AUTOMATOR "+wersja+"\n\n";
        
        //do późniejszego usunięcia w kolejnych wersjach
        log = log + "UWAGA! WERSJA BETA. PROSIMY O OSTROŻNOŚĆ.\n\n";

        log = log + "INFORMACJE O PLANOWANEJ OPERACJI:\n";
        
        log = log + "ŚCIEŻKA APARATU: "+ path +"\n"
                + "ILOŚĆ PLIKÓW PLANOWANYCH DO KOPIOWANIA: "+ Integer.toString(to_copy.size());
        wersja_label.setText(wersja);
        log_panel.setText(log);
        setVisible(true);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log_panel = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        zakoncz_button = new javax.swing.JButton();
        rozpocznij_button = new javax.swing.JButton();
        wersja_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Automator");

        jScrollPane1.setViewportView(log_panel);

        jLabel2.setText("Log:");

        zakoncz_button.setText("Zakończ");

        rozpocznij_button.setText("Rozpocznij");
        rozpocznij_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rozpocznij_buttonActionPerformed(evt);
            }
        });

        wersja_label.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(zakoncz_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wersja_label)))
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(rozpocznij_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(wersja_label))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rozpocznij_button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(zakoncz_button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rozpocznij_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rozpocznij_buttonActionPerformed
        for (Photo plik: file_list ){
            if(!plik.check_for_duplicates_e(path)){
                //operacja kopiowania
                if(new File(path+"\\"+plik.dir_name(actual_c.get_date_format())).exists()){
                    try {
                        Files.copy(plik.photo.toPath(), new File(path+"\\"+plik.dir_name(actual_c.get_date_format())+"\\"+plik.photo.getName()).toPath(),StandardCopyOption.REPLACE_EXISTING);
                    } catch (IOException ex) {
                        Logger.getLogger(automator_window.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    log = log +"SKOPIOWANO"+plik.name+"\n";
                    log_panel.setText(log);
                }
                else{
                    new File(path+"\\"+plik.dir_name(actual_c.get_date_format())).mkdir();
                    log = log + "UTWORZONO FOLDER: "+plik.dir_name(actual_c.get_date_format())+"\n";
                    try {
                        Files.copy(plik.photo.toPath(), new File(path+"\\"+plik.dir_name(actual_c.get_date_format())+"\\"+plik.photo.getName()).toPath(),StandardCopyOption.REPLACE_EXISTING);
                    } catch (IOException ex) {
                        Logger.getLogger(automator_window.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    log = log +"SKOPIOWANO"+plik.name+"\n";
                    log_panel.setText(log);
                }
                
                log = log + "KOPIUJE PLIK: "+plik.name+"\n"
                        +"WYKRYTA DATA: "+plik.photo_date+"\n";
                log_panel.setText(log);
            }
            else{
                log = log + "POMINIETO PLIK: "+plik.photo_src+"\n"
                        +"-------->ZNALEZIONO DUPLIKAT";
                log_panel.setText(log);
                        
            }
        }
        log = log + "OPERACJA ZAKONCZONA.\n";
        log_panel.setText(log);
    }//GEN-LAST:event_rozpocznij_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane log_panel;
    private javax.swing.JButton rozpocznij_button;
    private javax.swing.JLabel wersja_label;
    private javax.swing.JButton zakoncz_button;
    // End of variables declaration//GEN-END:variables
}
