/*
JAKUB WAWAK
ALL RIGHTS RESERVED.
kubawawak@gmail.com
 */
package photomator;

import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class background_window extends javax.swing.JFrame {

    /**
     * Creates new form background_window
     */
    
    Configuration act_con;
    
    public background_window() {
        super("PhotoMator");
        initComponents();
        
        act_con = new Configuration();
        
        if(act_con.wersja.contains("beta")){
            JOptionPane.showMessageDialog(this, "Wersja beta - zalecane ostrożne używanie");
        }
        
        setExtendedState(Frame.MAXIMIZED_BOTH);
        jLabel2.setText(act_con.wersja);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        rozpocznij_kopiowanie_jMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        wyswietl_jMenu = new javax.swing.JMenuItem();
        zarzadzaj_jMenu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        preferencje_jMenu = new javax.swing.JMenuItem();
        informacje_jMenu = new javax.swing.JMenuItem();
        zglos_uwagi_jMenu = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        jLabel1.setText("PhotoMator");

        jLabel2.setText("jLabel2");

        jMenu1.setText("Akcje");

        rozpocznij_kopiowanie_jMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        rozpocznij_kopiowanie_jMenu.setText("Rozpocznij Kopiowanie");
        rozpocznij_kopiowanie_jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rozpocznij_kopiowanie_jMenuActionPerformed(evt);
            }
        });
        jMenu1.add(rozpocznij_kopiowanie_jMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("PhotoMator Presets");

        wyswietl_jMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        wyswietl_jMenu.setText("Wyświetl Wszystkie");
        wyswietl_jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyswietl_jMenuActionPerformed(evt);
            }
        });
        jMenu2.add(wyswietl_jMenu);

        zarzadzaj_jMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.ALT_MASK));
        zarzadzaj_jMenu.setText("Zarządzaj");
        zarzadzaj_jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zarzadzaj_jMenuActionPerformed(evt);
            }
        });
        jMenu2.add(zarzadzaj_jMenu);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Opcje");

        preferencje_jMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        preferencje_jMenu.setText("Preferencje");
        preferencje_jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencje_jMenuActionPerformed(evt);
            }
        });
        jMenu4.add(preferencje_jMenu);

        informacje_jMenu.setText("Informacje");
        informacje_jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacje_jMenuActionPerformed(evt);
            }
        });
        jMenu4.add(informacje_jMenu);

        zglos_uwagi_jMenu.setText("Zgłoś Uwagi");
        zglos_uwagi_jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zglos_uwagi_jMenuActionPerformed(evt);
            }
        });
        jMenu4.add(zglos_uwagi_jMenu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel2)
                .addContainerGap(482, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(401, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rozpocznij_kopiowanie_jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rozpocznij_kopiowanie_jMenuActionPerformed
        new main_window();
    }//GEN-LAST:event_rozpocznij_kopiowanie_jMenuActionPerformed

    private void wyswietl_jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyswietl_jMenuActionPerformed
        new wyswietl_presets_window(this,true);
    }//GEN-LAST:event_wyswietl_jMenuActionPerformed

    private void zarzadzaj_jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zarzadzaj_jMenuActionPerformed
        new zarzadzaj_presets_window(this,true);
    }//GEN-LAST:event_zarzadzaj_jMenuActionPerformed

    private void preferencje_jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferencje_jMenuActionPerformed
        new preferencje_window(this,true);
    }//GEN-LAST:event_preferencje_jMenuActionPerformed

    private void informacje_jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacje_jMenuActionPerformed
        JOptionPane.showMessageDialog(this, "By Jakub Wawak "+ act_con.wersja);
    }//GEN-LAST:event_informacje_jMenuActionPerformed

    private void zglos_uwagi_jMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zglos_uwagi_jMenuActionPerformed
        JOptionPane.showMessageDialog(this, "Jeszcze niedostępne.");
    }//GEN-LAST:event_zglos_uwagi_jMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem informacje_jMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem preferencje_jMenu;
    private javax.swing.JMenuItem rozpocznij_kopiowanie_jMenu;
    private javax.swing.JMenuItem wyswietl_jMenu;
    private javax.swing.JMenuItem zarzadzaj_jMenu;
    private javax.swing.JMenuItem zglos_uwagi_jMenu;
    // End of variables declaration//GEN-END:variables
}
