/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package photomator;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class preferencje_window extends javax.swing.JDialog {

    /**
     * Creates new form preferencje_window
     */
    
    Configuration act = new Configuration();
    
    public preferencje_window(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if(act.save_log()){
            log_systemu_button.setText("Log systemu włączony");
        }
        else{
            log_systemu_button.setText("Log systemu wyłączony");
        }
        setLocationRelativeTo(null);
        jLabel2.setText(act.wersja);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data_format_set_button = new javax.swing.JButton();
        imie_set_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        log_systemu_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        data_format_set_button.setText("Zmień domyślny format nazwy folderu");
        data_format_set_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_format_set_buttonActionPerformed(evt);
            }
        });

        imie_set_button.setText("Zmień imie użytkownika");
        imie_set_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imie_set_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Preferencje");

        jLabel2.setText("jLabel2");

        log_systemu_button.setText("Log systemu włączony");
        log_systemu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_systemu_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(data_format_set_button, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(imie_set_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(log_systemu_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(data_format_set_button)
                .addGap(29, 29, 29)
                .addComponent(log_systemu_button)
                .addGap(27, 27, 27)
                .addComponent(imie_set_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_format_set_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_format_set_buttonActionPerformed
        new zmiana_formatu_window(null,true);
    }//GEN-LAST:event_data_format_set_buttonActionPerformed

    private void imie_set_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imie_set_buttonActionPerformed
        String nowe_imie = JOptionPane.showInputDialog("Podaj nowe imie:");
        try {
            act.configuration_file.zamien_wartosc("%imie", nowe_imie);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(preferencje_window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_imie_set_buttonActionPerformed

    private void log_systemu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_systemu_buttonActionPerformed
        if(act.save_log()){
            try {
                act.configuration_file.zamien_wartosc("%show_log", "no");
                log_systemu_button.setText("Log systemu wyłączony");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(preferencje_window.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else{
            try {
                act.configuration_file.zamien_wartosc("%show_log", "yes");
                log_systemu_button.setText("Log systemu włączony");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(preferencje_window.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_log_systemu_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton data_format_set_button;
    private javax.swing.JButton imie_set_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton log_systemu_button;
    // End of variables declaration//GEN-END:variables
}