/*
JAKUB WAWAK
ALL RIGHTS RESERVED.
kubawawak@gmail.com
 */
package photomator;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class welcome_window extends javax.swing.JDialog {

    /**
     * Creates new form welcome_window
     */
    String imie = "";
    int tabel_clicked = -1;
    String camera;
    String camera_path;
    
    boolean preset_made = false;
    
    DefaultListModel<String> model_tabeli = new DefaultListModel<>();
    
    public welcome_window(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        set_table_model();
        date_format_label.setText("");
        
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    void set_table_model(){
        model_tabeli.clear();
        
        model_tabeli.addElement("dzien/miesiac/rok");
        model_tabeli.addElement("dzien.miesiac.rok");
        model_tabeli.addElement("miesiac/dzien/rok");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imie_field = new javax.swing.JTextField();
        make_preset_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        date_format_table = new javax.swing.JList<>();
        date_format_label = new javax.swing.JLabel();
        zaczynamy_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("PhotoMator");

        jLabel3.setText("Podaj Swoje Imie:");

        make_preset_button.setText("Utwórz PhotoMator Preset");
        make_preset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                make_preset_buttonActionPerformed(evt);
            }
        });

        jLabel4.setText("Wybierz domyślną formę formatu daty:");

        date_format_table.setModel(model_tabeli);
        date_format_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                date_format_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(date_format_table);

        date_format_label.setText("jLabel5");

        zaczynamy_button.setText("Zaczynamy");
        zaczynamy_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zaczynamy_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(make_preset_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(imie_field, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(zaczynamy_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(date_format_label)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(imie_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(make_preset_button)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(date_format_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zaczynamy_button)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void make_preset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make_preset_buttonActionPerformed
        camera = JOptionPane.showInputDialog(this,"Podaj nazwe aparatu");
        if(!camera.equals("")){
            JFileChooser myFileChooser = new JFileChooser();
            myFileChooser.setDialogTitle("Wybierz sciezke dla: "+camera);
            myFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

            if(myFileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
                String path = myFileChooser.getSelectedFile().getAbsolutePath();
                camera_path = path;
                preset_made = true;
                make_preset_button.setEnabled(false);
            }
            else{
                JOptionPane.showMessageDialog(this, "Nie wybrales pliku");
            }
            }
        else{
            JOptionPane.showMessageDialog(this, "Pole puste");
        }
    }//GEN-LAST:event_make_preset_buttonActionPerformed

    private void zaczynamy_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zaczynamy_buttonActionPerformed
        imie = imie_field.getText();
        if(tabel_clicked != -1 && preset_made == true && !imie.equals((""))){
            tabel_clicked++;
            Configuration act= new Configuration();
            ArrayList<String> t = new ArrayList<>();
            t.add(camera+" "+camera_path);       
            try {
                act.make_configuration(t, imie, Integer.toString(tabel_clicked));
                JOptionPane.showMessageDialog(this, "Konfiguracja początkowa została zapisana");
                setVisible(false);
                dispose();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(welcome_window.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Dokonaj pełnej konfiguracji");
        }
    }//GEN-LAST:event_zaczynamy_buttonActionPerformed

    private void date_format_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date_format_tableMouseClicked
        tabel_clicked = date_format_table.getSelectedIndex();
        date_format_label.setText(date_format_table.getSelectedValue());
    }//GEN-LAST:event_date_format_tableMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_format_label;
    private javax.swing.JList<String> date_format_table;
    private javax.swing.JTextField imie_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton make_preset_button;
    private javax.swing.JButton zaczynamy_button;
    // End of variables declaration//GEN-END:variables
}
