/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package photomator;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class zarzadzaj_presets_window extends javax.swing.JDialog {

    /**
     * Creates new form zarzadzaj_presets_window
     */
    DefaultListModel<String> model_tabeli = new DefaultListModel<>();
    
    Configuration act;
    
    String selected = "";
    
    public zarzadzaj_presets_window(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        act = new Configuration();
        initComponents();
        
        reload();
        
        setVisible(true);
    }
    
    void reload(){
        model_tabeli.clear();
        for (String s: act.get_presets_names()){
            model_tabeli.addElement(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JList<>();
        dodaj_button = new javax.swing.JButton();
        usun_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabela.setModel(model_tabeli
        );
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        dodaj_button.setText("Dodaj");
        dodaj_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodaj_buttonActionPerformed(evt);
            }
        });

        usun_button.setText("Usun");
        usun_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usun_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Twoje Presety");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dodaj_button, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usun_button, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dodaj_button, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usun_button, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodaj_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodaj_buttonActionPerformed
        String camera,camera_path;
        camera = JOptionPane.showInputDialog(this,"Podaj nazwe aparatu");
        if(!camera.equals("")){
            JFileChooser myFileChooser = new JFileChooser();
            myFileChooser.setDialogTitle("Wybierz sciezke dla: "+camera);
            myFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

            if(myFileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
                String path = myFileChooser.getSelectedFile().getAbsolutePath();
                camera_path = path;
                
                try {
                    act.configuration_file.dodaj("%presets", camera+" "+camera_path);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(zarzadzaj_presets_window.class.getName()).log(Level.SEVERE, null, ex);
                }
                act = new Configuration();
                reload();
            }
            else{
                JOptionPane.showMessageDialog(this, "Nie wybrales pliku");
            }
            }
        else{
            JOptionPane.showMessageDialog(this, "Pole puste");
        }
    }//GEN-LAST:event_dodaj_buttonActionPerformed

    private void usun_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usun_buttonActionPerformed
        if(!selected.equals("")){
            try {
                act.configuration_file.usun_wartosc("%presets", selected);
                reload();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(zarzadzaj_presets_window.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Nic nie zostało zaznaczone");
        }
    }//GEN-LAST:event_usun_buttonActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        selected = tabela.getSelectedValue();
    }//GEN-LAST:event_tabelaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodaj_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> tabela;
    private javax.swing.JButton usun_button;
    // End of variables declaration//GEN-END:variables
}
